# vim: set ts=2 sw=2 ai si et ft=yaml:
---

remote_theme: raviriley/agency-jekyll-theme

url: "https://dleidert.dev"
baseurl: ""

title: Daniel Leidert (Freelancer)
tagline: Ihr Debian und Ubuntu Spezialist
description: Support rund um Debian und Ubuntu und Raspbian und Derivate, Systemadministration, Backups, Härten, Netzwerke, DevOps, CI/CD und mehr
author:
  name: Daniel Leidert
  url: https://dleidert.dev
email: daniel.leidert@dleidert.dev

# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

social:
  name: Daniel Leidert
  links:
    - https://www.fiverr.com/dleidert
    - https://www.xing.com/profile/Daniel_Leidert
    - https://www.linkedin.com/in/daniel-leidert-8995952aa/
    - https://github.com/dleidert
    - https://gitlab.com/dleidert
    - https://salsa.debian.org/dleidert
    - https://keys.openpgp.org/search?q=daniel.leidert%40dleidert.dev

locale: "de"

collections:
  portfolio:

defaults:
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - legal.md.2
  - README.md
  - LICENSE
